version: '2'

volumes:
  db:
    driver: local

services:
  app:
    depends_on:
      - postgresdb
    build: .
    env_file: ./.env
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    volumes:
      - /etc/letsencrypt/live/geos.icc.ru/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/geos.icc.ru/privkey.pem:/certs/privkey.pem:ro
    environment:
      DB_HOST: postgresdb
      DB_USER: "$POSTGRESDB_USER"
      DB_PASSWORD: "$POSTGRESDB_ROOT_PASSWORD"
      DB_NAME: "$POSTGRESDB_DATABASE"
      DB_PORT: "$POSTGRESDB_DOCKER_PORT"
    restart: always

  postgresdb:
    image: postgres
    env_file: ./.env
    environment:
      POSTGRES_USER: "$POSTGRESDB_USER"
      POSTGRES_PASSWORD: "$POSTGRESDB_ROOT_PASSWORD"
      POSTGRES_DB: "$POSTGRESDB_DATABASE"
    ports:
      - "$POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT"
    volumes:
      - db:/var/lib/postgresql/data